#!/bin/sh

git clean -fdx && \
npm cache clear && \
npm i --no-optional && \
npm link --no-optional && \
npm pack && \
du -sh ./ember-cli-*.tgz && \
npm uninstall -g ember-cli && \
npm i -g ./ember-cli-*.tgz
