name: Setup environment
description: Setup environment

inputs:
  node-version:
    default: "20"
    description: Node version

runs:
  using: composite

  steps:
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v4
      with:
        cache: pnpm
        node-version: ${{ inputs.node-version }}

    - run: pnpm install
      shell: bash
