/*jshint multistr: true */

'use strict';

var expect            = require('chai').expect;
var EOL               = require('os').EOL;
var MockUI            = require('../../../helpers/mock-ui');
var MockAnalytics     = require('../../../helpers/mock-analytics');
var processHelpString = require('../../../helpers/process-help-string');
var HelpCommand       = require('../../../../lib/commands/help');
var DestroyCommand    = require('../../../../lib/commands/destroy');

describe('help command: destroy', function() {
  var ui, command;

  beforeEach(function() {
    ui = new MockUI();

    var options = {
      ui: ui,
      analytics: new MockAnalytics(),
      commands: {
        'Destroy': DestroyCommand
      },
      project: {
        isEmberCLIProject: function() {
          return true;
        }
      },
      settings: {}
    };

    command = new HelpCommand(options);
  });

  it('works', function() {
    return command.validateAndRun(['destroy']).then(function() {
      var output = ui.output;

      var testString = processHelpString(EOL + '\
ember destroy \u001b[33m<blueprint>\u001b[39m \u001b[36m<options...>\u001b[39m' + EOL + '\
  Destroys code generated by `generate` command.' + EOL + '\
  \u001b[90maliases: d\u001b[39m' + EOL + '\
  \u001b[36m--dry-run\u001b[39m \u001b[36m(Boolean)\u001b[39m \u001b[36m(Default: false)\u001b[39m' + EOL + '\
    \u001b[90maliases: -d\u001b[39m' + EOL + '\
  \u001b[36m--verbose\u001b[39m \u001b[36m(Boolean)\u001b[39m \u001b[36m(Default: false)\u001b[39m' + EOL + '\
    \u001b[90maliases: -v\u001b[39m' + EOL + '\
  \u001b[36m--pod\u001b[39m \u001b[36m(Boolean)\u001b[39m \u001b[36m(Default: false)\u001b[39m' + EOL + '\
    \u001b[90maliases: -p\u001b[39m' + EOL + '\
  \u001b[36m--classic\u001b[39m \u001b[36m(Boolean)\u001b[39m \u001b[36m(Default: false)\u001b[39m' + EOL + '\
    \u001b[90maliases: -c\u001b[39m' + EOL + '\
  \u001b[36m--dummy\u001b[39m \u001b[36m(Boolean)\u001b[39m \u001b[36m(Default: false)\u001b[39m' + EOL + '\
    \u001b[90maliases: -dum, -id\u001b[39m' + EOL + '\
  \u001b[36m--in-repo-addon\u001b[39m \u001b[36m(String)\u001b[39m \u001b[36m(Default: null)\u001b[39m' + EOL + '\
    \u001b[90maliases: -in-repo <value>, -ir <value>\u001b[39m' + EOL + '\
' + EOL + '\
' + EOL + '\
  Run `ember help generate` to view a list of available blueprints.' + EOL);

      expect(output).to.include(testString);
    });
  });

  it('works with alias d', function() {
    return command.validateAndRun(['d']).then(function() {
      var output = ui.output;

      var testString = processHelpString('ember destroy \u001b[33m<blueprint>\u001b[39m \u001b[36m<options...>\u001b[39m');

      expect(output).to.include(testString);
    });
  });
});
